language: java

sudo: required

jdk:
  - openjdk14

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'

script:
  - "./mvnw clean test"

#after_success:
#  - bash <(curl -s https://codecov.io/bash)